name: Build & Test

on:
  push:
  schedule:
  - cron:  '0 3 * * 1'


jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python setup.py install
    - name: Test with pytest
      run: |
        pip install pytest
        pytest ./test
